"""empty message

Revision ID: 75c763683ff0
Revises: 
Create Date: 2017-12-17 09:59:19.188820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c763683ff0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('shoppinglist_id', sa.Integer(), nullable=True))
    op.drop_constraint('Product_shoppinglist_fkey', 'Product', type_='foreignkey')
    op.create_foreign_key(None, 'Product', 'Shoppinglists', ['shoppinglist_id'], ['id'])
    op.add_column('Shoppinglists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('Shoppinglists_user_fkey', 'Shoppinglists', type_='foreignkey')
    op.create_foreign_key(None, 'Shoppinglists', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shoppinglists', type_='foreignkey')
    op.create_foreign_key('Shoppinglists_user_fkey', 'Shoppinglists', 'User', ['user'], ['username'])
    op.drop_column('Shoppinglists', 'user_id')
    op.drop_constraint(None, 'Product', type_='foreignkey')
    op.create_foreign_key('Product_shoppinglist_fkey', 'Product', 'Shoppinglists', ['shoppinglist'], ['shoppinglist_name'])
    op.drop_column('Product', 'shoppinglist_id')
    # ### end Alembic commands ###
